openapi: 3.0.0
info:
  title: Notification Server API
  description: API for managing real-time notifications and WebSocket connections
  version: 1.0.0
  contact:
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: Development server

components:
  schemas:
    Notification:
      type: object
      required:
        - id
        - channel
        - message
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the notification
        channel:
          type: string
          description: Channel name the notification belongs to
        message:
          type: string
          description: Notification message content
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp in milliseconds

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message

paths:
  /api/notifications:
    post:
      summary: Publish a new notification
      description: Creates and broadcasts a new notification to a channel
      operationId: publishNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channel
                - message
              properties:
                channel:
                  type: string
                  description: Channel to publish the notification to
                message:
                  type: string
                  description: Notification message content
      responses:
        '201':
          description: Notification published successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/notifications/{channel}:
    get:
      summary: Get notification history
      description: Retrieves recent notifications for a specific channel
      operationId: getNotifications
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
          description: Channel name
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Maximum number of notifications to return
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/channels/{channel}/subscribe:
    post:
      summary: Subscribe to a channel
      description: Subscribe a client to receive notifications from a channel
      operationId: subscribeToChannel
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
          description: Channel name to subscribe to
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientId
              properties:
                clientId:
                  type: string
                  description: WebSocket client ID
      responses:
        '200':
          description: Successfully subscribed to channel
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/channels/{channel}/unsubscribe:
    post:
      summary: Unsubscribe from a channel
      description: Unsubscribe a client from receiving notifications from a channel
      operationId: unsubscribeFromChannel
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
          description: Channel name to unsubscribe from
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientId
              properties:
                clientId:
                  type: string
                  description: WebSocket client ID
      responses:
        '200':
          description: Successfully unsubscribed from channel
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 